### ISSUE TITLE
Multitouch does not work when dragging

### ISSUE THREAD

**Issue by celyk** [xibbon/XogotIssues#24]
Touch event `InputEventScreenDrag` doesn't fire when using more than 1 finger to touch the screen, however the gesture events do.

You can use this MRP to display the touches in Godot as points (offset for visibility)
https://github.com/godotengine/godot/files/14965849/godot-display-touch-events.zip

**My specs**
iPad 9th gen
iPadOS 18.0

**Comment by andrekling** [comment]
2 fingers interaction gets locked to the first movement made, so either it zooms or pan, depending if you move your fingers apart or drag them, as a user I would expect to be Able to perform both at the same time, zooming and panning, this is the kind of navigation found on nomad, zbrush for iPad and so on.

**Comment by andrekling** [comment]
The only way to go from panning to zoom is to stop the action by lifting the fingers from the screen and start again being careful not to activate the undesired option, this slows down the workflow

**Comment by celyk** [comment]
I agree. This appears to be true of InputGestureEvents as well, as I am using them in my project and I face the same problem.

The way we want it is for each InputGestureEvent to be a convenience that recognizes the gesture, but does not exclude other events from firing. I'm pretty sure there are options in SwiftUI to do that.

**Comment by migueldeicaza** [comment]
Fixed, build coming up.

**Comment by migueldeicaza** [comment]
My bad, the bug is not fixed.

**Comment by migueldeicaza** [comment]
Bug has been fixed, coming up.

**Comment by celyk** [comment]
While InputEventScreenDrag events now fire, some InputEventScreenTouch don't anymore. Specifically the initial touches of more than 1 finger. As of build 1765 this is still a problem

**Comment by celyk** [comment]
Getting different behaviour on web builds. The initial touches fire properly, but event.index appears to be uninitialized garbage: `index=-526212702`

I noticed that the value increments by +1 each time I touch, and it persists even after reloading the page.

<img width="735" alt="Image" src="https://github.com/user-attachments/assets/fd51fc3d-a881-4a8f-be24-c80132b66a7d" />
